config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :cards, only: :create
    resources :sales, only: :update do
      post :authorize, on: :collection
      post :confirm, on: :collection
    end
  end

  resources :users do
    collection do
      get :search
    end
    member do
      patch :assign_card
      get :edit_points
      put :update_points
    end
    resources :services, except: [:index] do
      put :activate, on: :member
      put :finalize, on: :member
    end
    resources :sales, except: [:edit, :destroy, :update] do
      resources :sale_products
    end
  end

  resources :laboratories, only: [] do
    get :search, on: :collection
  end

  resources :drugs, only: [] do
    get :search, on: :collection
  end

  resources :services, only: [] do
    get :near_expiration, on: :collection
    get :history, on: :member
  end

  get 'my_purchases', to: 'sales#index'

  resources :health_insurances, only: [:show, :create, :update] do
    collection do
      get :search
    end
  end

  resources :coinsurances, only: [:show, :create, :update] do
    collection do
      get :search
    end
  end

  resources :pathologies, except: [:show]

  resources :products, except: [] do
    collection do
      get :search
      get :search_for_service
      get :new_batch_update
      post :batch_update
    end
  end

  resources :alfabeta_updates, only: [:index, :show]

  get 'rewards/:id/down_stock', to: 'rewards#down_stock', as: :reward_down_stock
  get 'rewards/:id/up_stock', to: 'rewards#up_stock', as: :reward_up_stock
  post 'rewards/down_stock_update', to: 'rewards#down_stock_update', as: :reward_down_stock_update
  post 'rewards/up_stock_update', to: 'rewards#up_stock_update', as: :reward_up_stock_update
  resources :rewards

  resources :shopping_cart_rewards, except: [:index, :new, :edit, :create, :destroy, :update] do
    get :add_item, on: :member
    get :refresh_item, on: :member
    get :delete_item, on: :member
    get :list, on: :collection
    get :shoping_cart, on: :collection
    post :confirm_shoping_cart, on: :collection
  end

  resources :reward_orders, only: [:index, :show, :destroy] do
    get :change_state, on: :member
    get :voucher_pdf, on: :member
  end

  resources :vademecums do
    get :get_suppliers, on: :member
  end

  resources :supplier_requests, except: [:destroy] do
    member do
      post :add_card
      post :emit
    end
    resources :comments, only: [:create, :index]
  end

  resources :comments, only: [:destroy]

  resources :suppliers do
    get :list_for_map, on: :collection
    get :search, on: :collection
    resources :users do
      resources :sales, except: [:edit, :destroy, :update] do
        resources :sale_products
      end
    end
    resources :supplier_requests do
      collection do
        get :document_form
        post :load_form
      end
    end
    resources :services do
      get :near_expiration, on: :collection
    end
  end

  resources :authorizations, except: [:destroy, :update, :edit, :new]

  resources :sessions, only: :create

  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'admin', to: 'application#admin', as: :admin
  get 'profile', to: 'users#edit', as: :profile

  get 'login', to: 'sessions#login_form', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  get 'no_cards_assigned', to: 'public#no_cards_assigned', as: :no_cards_assigned
  get 'terms_of_use', to: 'public#terms_of_use', as: :terms_of_use
  post 'accept_terms_of_use', to: 'public#accept_terms_of_use', as: :accept_terms_of_use
  root 'public#home'

end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id                        :integer          not null, primary key
#  name                      :string(255)      not null
#  type                      :string(255)      not null
#  user_id                   :integer
#  last_period_id            :integer
#  amount                    :float(24)
#  status                    :integer          default(0)
#  days                      :integer          default(30)
#  days_to_points_expiration :integer
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  vademecum_id              :integer
#

class Service < ActiveRecord::Base

  # -- Scopes
  default_scope { order(:name) }
  scope :in_progress, -> { where(status: Service.statuses['in_progress']) }
  scope :pending, -> { where(status: Service.statuses['pending']) }
  scope :available, -> { where(status: [Service.statuses['pending'], Service.statuses['in_progress']]) }
  scope :finished, -> { where(status: [Service.statuses['expired'], Service.statuses['closed']]) }

  # -- Constants
  TYPES = %w(points pfpc seller)

  # -- Associations
  belongs_to :user

  # -- Validations
  validates :name, :user, :days, presence: true

  # Statuses
  # pending: Servicio creado pero no habilitado (default)
  # in_progress: En curso
  # expired: Servicio vencido. No se cumplió el objetivo en el último período
  # closed: Servicio cerrado/deshabilitado manualmente
  enum status: {pending: 0, in_progress: 1, expired: 2, closed: 3}

  def to_s
    name
  end

  # Cambia el estado del servicio
  def mark_as(status)
    self.status = status
    self.save
  end

  def can_be_activated?
    true
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_action :set_supplier
  before_action :set_user
  before_action :set_service, only: [:show, :edit, :update, :destroy, :activate, :finalize, :history]
  before_action :only_authorize_god!, except: [:show, :near_expiration, :history]
  before_action :only_authorize_admin!, only: [:near_expiration]

  # GET /users/X/services/new
  def new
    if params_type == 'seller'
      create_seller_service # Se crea sin necesidad de formulario
    else
      @service = build_service
    end
  end

  # POST /users/X/services/new
  def create
    @service = build_service(service_params)
    @service.user = @user

    respond_to do |format|
      if @service.save
        format.html { redirect_to [@user, @service], notice: 'El servicio ha sido creado correctamente.' }
      else
        format.html { render :new }
      end
    end
  end

  # GET /users/2/services/1
  def show
    authorize!(admin_permission? || is_mine?)
    if is_mine? && normal_user?
      render layout: 'public'
    end
  end

  # GET /users/2/services/1/edit
  def edit
  end

  # GET /users/2/services/1/edit_products
  def edit_products
  end

  # PATCH/PUT /users/2/services/1
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to [@user, @service], notice: 'El servicio ha sido actualizado correctamente.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1/services/1
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to @user, notice: 'El servicio ha sido eliminado correctamente.' }
    end
  end

  # PUT /users/1/services/1/activate
  def activate
    ActiveRecord::Base.transaction do
      if @service.pending?
        unless @service.can_be_activated?
          flash[:error] = 'El servicio no puede ser activado.'
          redirect_to [@user, @service]
          return false
        else
          @service.last_period.restart
          @service.mark_as(:in_progress)
        end
      else
        @service.last_period.renew
      end
      @service.mark_as(:in_progress)
    end
    redirect_to [@user, @service], notice: 'El servicio ha sido activado.'
  end

  # PUT /users/1/services/1/finalize
  def finalize
    ActiveRecord::Base.transaction do
      @service.last_period.mark_as(:closed)
      @service.mark_as(:closed)
    end
    redirect_to [@user, @service], notice: 'El servicio ha sido finalizado.'
  end

  # GET /services/near_expiration
  # Muestra los servicios próximos a vencer
  def near_expiration
    @filter = NearExpirationFilter.new(filter_params)
    @services = @filter.call(@supplier).page(params[:page])

    respond_to do |format|
      format.xlsx
      format.html
    end
  end

  # GET /services/X/history
  # Muestra el historial de períodos
  def history
    authorize!(admin_permission? || is_mine?)
    @periods = @service.periods.not_in_progress.recents
  end

  private

  def params_type
    params[:type] || params[:service][:type]
  end

  def build_service(parameters=nil)
    (params_type == 'pfpc' || params_type == 'PfpcService') ? PfpcService.new(parameters) : PointsService.new(parameters)
  end

  def create_seller_service
    SellerService.create_for!(@user)
    redirect_to @user, notice: 'Se ha creado el servicio'
  rescue Exception => e
    flash[:error] = e.message
    redirect_to @user
  end

  def set_user
    if params[:user_id]
      @user = User.find(params[:user_id])
    end
  end

  def set_supplier
    if params[:supplier_id]
      @supplier = Supplier.find(params[:supplier_id])
    end
  end

  def set_service
    @service = Service.find(params[:id])
  end

  def is_mine?
    current_user == @service.user
  end

  def service_params
    allowed_params = [:name, :days]

    if params[:service][:type] == 'PointsService'
      params[:service][:days_to_points_expiration] = params[:days_to_points_expiration]
      allowed_params << :amount << :days_to_points_expiration
    else
      allowed_params << :vademecum_id << [product_pfpcs_attributes: [:id, :product_id, :amount, :_destroy]] << [pfpc_suppliers_attributes: [:id, :supplier_id, :_destroy]]
    end

    params.require(:service).permit(allowed_params)
  end

  def filter_params
    params.require(:near_expiration_filter).permit(:supplier_id, :date) if params[:near_expiration_filter]
  end
end

app/helpers/service_helper.rb
module ServiceHelper

  def available_services_for(user)
    service_types = Service::TYPES
    service_types = service_types - ['seller'] unless user.is?([:god, :seller])
    service_types
  end

end

app/views/services/_filter.html.erb
<div id="js-nearExpirationFilter">
  <%= form_for @filter, url: [:near_expiration, @supplier, :services], method: :get do |f| %>

      <%= hidden_field_tag :format, '', id: 'js-nearExpirationFormat' %>

      <div class="row">
        <% if god? %>
            <div class="col-md-4">
              <fieldset class="form-group">
                <%= f.label :supplier_id %>
                <%= f.collection_select :supplier_id, Supplier.all,
                                        :id, :name, {include_blank: true}, {class: 'form-control'} %>
              </fieldset>
            </div>
        <% end %>
        <div class="col-md-3">
          <fieldset class="form-group">
            <%= f.label :date %>
            <%= f.text_field :date, {type: :date, class: 'form-control'} %>
          </fieldset>
        </div>
        <div class="col-md-4">
          <fieldset class="form-group">
            <%= f.label :filter %><br/>
            <%= f.submit 'Filtrar', class: 'btn btn-primary', data: {behavior: 'filter', 'disable-with' => 'Filtrando'} %>
            <%= f.submit 'Exportar', class: 'btn btn-info', data: {behavior: 'export'} %>
          </fieldset>
        </div>
      </div>

  <% end %>
</div>

app/views/services/_form.html.erb
<div class="row">
  <div class="col-md-9">
    <article class="box box-primary">
      <section class="box-body">

      <%= form_for [@user, @service] do |f| %>
        <% @service.errors.full_messages.each do |message| %>
          <p class="text-danger"><%= message %></p>
        <% end %>
  
        <%= f.hidden_field :type %>

        <div class="row">
          <fieldset class="form-group col-md-10">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', required: true %>
          </fieldset>
    
          <fieldset class="form-group col-md-2">
            <%= f.label :days %>
            <%= f.number_field :days, id: 'js-daysPerPeriod', class: 'form-control', required: true %>
          </fieldset>
        </div>
        
        <% if @service.is_a?(PfpcService) %>
          <%= render 'pfpc_form', f: f %>
        <% else %>
          <%= render 'points_form', f: f %>
        <% end %>

        <div class="actions">
          <%= f.submit 'Guardar servicio', class: 'btn btn-primary', data: { 'disable-with' => 'Cargando...' } %>
        </div>
      <% end %>

      </section>
    </article>
  </div>
  
  <% if content_for?(:form_help) %>
    <div class="col-md-3">
      <%= yield :form_help %>
    </div>
  <% end %>
  
</div>

app/views/services/_history.html.erb
<ul class="timeline">
  
  <% @periods.each do |period| %>
    <li>
      <% if period.expired? || period.closed? %>
        <i class="fa fa-times bg-red"></i>
      <% else %>
        <i class="fa fa-check bg-green"></i>
      <% end %>

      <div class="timeline-item">
        
        <span class="time"><i class="fa fa-calendar-o"></i> <%= l period.end_date %></span>
        
        <h3 class="timeline-header text-left"> <%= t period.status, scope: 'service_periods_statuses' %> </h3>

        <div class="timeline-body">
          <% if @service.is_a?(PointsService) %>
            <%= render partial: 'points_period', locals: { period: period } %>
          <% else %>
            <%= render partial: 'pfpc_period', locals: { period: period } %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  
  <li>
    <i class="fa fa-clock-o bg-gray"></i>
  </li>
</ul>

app/views/services/_inactive_service.html.erb
<div class="alert alert-danger alert-dismissible">
  <h4> Servicio no Activo </h4>
  El servicio no se encuentra activo o ha vencido. 
</div>

<% if god? %>
  <% btn_text = @service.pending? ? 'Iniciar' : 'Renovar' %>
  <%= link_to [:activate, @user, @service], method: :put, class: 'btn btn-block btn-info' do %>
    <i class="fa fa-check"></i> <%= btn_text %>
  <% end %>
<% end %>

app/views/services/_pfpc_form.html.erb
<div class="row">
  <fieldset class="form-group col-md-5">
    <%= f.label :vademecum %>
    <%= f.collection_select :vademecum_id, Vademecum.all, :id, :name, {prompt: 'Seleccione un vademecum'}, {class: 'form-control', id: 'js-vademecumField'} %>
  </fieldset>
</div>

<div class="row">
  <div class="col-md-7"> <%= label_tag :products, 'Producto' %> </div>
  <div class="col-md-3"> <%= label_tag :products, 'Cantidad' %> </div>
</div>

<div id="js-productPfpcs" class="product_pfpcs form-group">
  <%= f.fields_for :product_pfpcs do |p| %>
      <%= render 'product_pfpc_fields', f: p %>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'Nuevo Producto', f, :product_pfpcs, class: 'btn btn-default' %>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-md-10"> <%= label_tag :suppliers, 'Prestador' %></div>
</div>

<div id="js-pfpcSuppliers" class="pfpc_suppliers form-group">
  <%= render partial: 'pfpc_suppliers/form', locals: {f: f} %>
</div>

<%= content_for(:form_help) do %>
    <div class="callout callout-warning">
      <h4>Notas</h4>

      <p>
        Los productos serán filtrados por el <b>Vademecum seleccionado</b>.
      </p>

      <p>
        Los productos previamente añadidos a otro servicio no están disponibles para la selección.
      </p>
    </div>
<% end %>

app/views/services/_pfpc_products_form.html.erb
<div class="row">
  <fieldset class="form-group col-md-5">
    <%= f.label :vademecum %>
    <%= f.collection_select :vademecum_id, Vademecum.all, :id, :name, {}, {class: 'form-control'} %>
  </fieldset>
</div>

<div class="row">
  <div class="col-md-7"> <%= label_tag :products, 'Producto' %> </div>
  <div class="col-md-3"> <%= label_tag :products, 'Cantidad' %> </div>
</div>

<div class="product_pfpcs  form-group">
  <%= f.fields_for :product_pfpcs do |p| %>
    <%= render 'product_pfpc_fields', f: p %>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'Nuevo Producto', f, :product_pfpcs, class: 'btn btn-default' %>
  </div>
</div>

app/views/services/_pfpc_supplier_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-md-7">
      <fieldset class="form-group">
        <%= f.select :supplier_id,
				    Supplier.all.map{ |s| [s.name, s.id] },
						  {include_blank: true}, {class: 'form-control'} %>									
      </fieldset>
    </div>
    
    <div class="col-md-1">
      <fieldset class="form-group">
        <%= link_to_remove_association 'eliminar', f, class: 'btn btn-danger' %>
      </fieldset>
    </div>
    
  </div>
</div>

app/views/services/_points_form.html.erb
<div class="row">
  <fieldset class="form-group col-md-4">
    <%= f.label :amount %>
    <%= f.number_field :amount, class: 'form-control', required: true %>
  </fieldset>

  <fieldset class="form-group col-md-4">
    <%= label_tag 'Períodos en vencer' %>
    <%= number_field_tag :period_count, '1', id: 'js-periodCount', class: 'form-control', required: true %>
  </fieldset>

  <fieldset class="form-group col-md-4">
    <%= label_tag 'Días en vencer' %>
    <p id="js-pointsExpirationVisible" class="form-control-static">1</p>
    <%= hidden_field_tag :days_to_points_expiration, '', id: 'js-pointsExpiration', required: true %>
  </fieldset>

</div>

<%= content_for(:form_help) do %>
    <div class="callout callout-warning">
      <h4>Notas</h4>
      <p>
        Se podrán crear varios servicios de puntos para un usuario pero sólo se podrá tener un único servicio activo.
      </p>
    </div>
<% end %>

app/views/services/_product_pfpc_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-md-7">
      <fieldset class="form-group">
        <%= f.hidden_field :product_id, class: 'form-control select2',
                           data: {behavior: 'searchProduct', url: search_for_service_products_path(user_id: @user.id),
                                  record_id: f.object.product_id, record_text: f.object.product.try(:name),
                           } %>
      </fieldset>
    </div>

    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.text_field :amount, class: 'form-control', required: true, placeholder: 'Cantidad' %>
      </fieldset>
    </div>

    <div class="col-md-1">
      <fieldset class="form-group">
        <%= link_to_remove_association 'eliminar', f, class: 'btn btn-danger' %>
      </fieldset>
    </div>

  </div>
</div>

app/views/services/_service.html.erb
<tr>
  <td>
    <%= link_to service.user [@supplier, service.user] do %>
      <%= t service.user.document_type, scope: :document_types %>
      <%= service.user.document_number %> -
      <%= service.user %> 
    <% end %>
  </td>
  <td> <%= service.user.email %> </td>
  <td> <%= t service.type, scope: :service_types %> </td>
  <td> <%= link_to service, [service.user, service] %> </td>

  <% if service.user.is?('seller') || service.user.is?('admin') %>
    <td>-</td>
  <% else %>
    <td> <%= l service.last_period.end_date %> </td>
  <% end %>

  <% unless @supplier %>
    <td> <%= service.user.supplier %> </td>
  <% end %>
</tr>

app/views/services/edit.html.erb
<header class="content-header">
  <%= link_to 'Volver', @user, class: 'btn btn-default pull-right' %>
  <h1>Editar Servicio</h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>

app/views/services/history.js.erb
$('#js-history').html('<%= j render "history" %>')

app/views/services/near_expiration.html.erb
<header class="content-header">
  <% if @supplier %>
      <h1>Servicios por vencer de <%= @supplier.name %></h1>
  <% else %>
      <h1>Servicios por vencer</h1>
  <% end %>
</header>

<!-- Main content -->
<section class="content">
  <article class="box box-primary">
    <section class="box-body">

      <%= render 'filter' %>

      <table class="table">
        <thead>
        <tr>
          <th>Usuario</th>
          <th>Correo electrónico</th>
          <th>Tipo Servicio</th>
          <th>Servicio</th>
          <th>Vencimiento</th>
          <% unless @supplier %>
              <th>Prestador</th>
          <% end %>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <%= render partial: 'service', collection: @services, as: 'service' %>
        </tbody>
      </table>

      <%= paginate @services %>

    </section>
  </article>
</section>

<% if @services.empty? && params[:near_expiration_filter] %>
    <p class="text-center text-muted lead">
      No se encontraron resultados
    </p>
<% end %>

app/views/services/show.html.erb
<header class="content-header">
  <%= link_to 'Volver', @user, class: 'btn btn-default pull-right' %>
  <h1>
    Información de servicio
    <% unless normal_user? %>
        <small> <%= @user %></small>
    <% end %>
  </h1>

</header>

<% klass = (@service.in_progress?) ? 'success' : 'danger' %>

<section class="content">

  <div class="row">
    <div class="col-md-7">
      <article class="box box-<%= klass %>">
        <section class="box-body box-profile">
          <h3 class="profile-username text-center">
            <%= @service.name %>
          </h3>

          <%= render @service %>

        </section>

        <div class="box-footer">
          <% if god? %>
              <%= link_to 'Editar', [:edit, @user, @service], class: 'btn btn-success' if @service.pending? %>
              <%= link_to 'Finalizar', [:finalize, @user, @service], class: 'btn btn-info', method: :put if @service.in_progress? && !@service.is_a?(SellerService) %>
              <%= link_to 'Eliminar', [@user, @service], method: :delete, class: 'btn btn-danger', data: {confirm: '¿Está seguro?'} %>
          <% end %>
        </div>
      </article>
    </div>

    <% unless @service.is_a?(SellerService) %>
      <div class="col-md-5">
        <article class="box box-<%= klass %>">
          <section class="box-body box-profile">
            <h3 class="profile-username text-center">
              Período Actual
            </h3>

            <% if !@service.in_progress? %>
                <%= render 'inactive_service' %>
            <% else %>
              <%= render @service.last_period %>
            <% end %>
          </section>
        </article>

        <div id="js-history" class="text-center">
          <% periods_count = @service.periods.not_in_progress.count %>
          <% unless periods_count == 0 %>
              <%= link_to "Ver Historial (#{periods_count} más)", history_service_path(@service), remote: true, data: {'diable-with' => 'Cargando...'} %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</section>