config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :cards, only: :create
    resources :sales, only: :update do
      post :authorize, on: :collection
      post :confirm, on: :collection
    end
  end

  resources :users do
    collection do
      get :search
    end
    member do
      patch :assign_card
      get :edit_points
      put :update_points
    end
    resources :services, except: [:index] do
      put :activate, on: :member
      put :finalize, on: :member
    end
    resources :sales, except: [:edit, :destroy, :update] do
      resources :sale_products
    end
  end

  resources :laboratories, only: [] do
    get :search, on: :collection
  end

  resources :drugs, only: [] do
    get :search, on: :collection
  end

  resources :services, only: [] do
    get :near_expiration, on: :collection
    get :history, on: :member
  end

  get 'my_purchases', to: 'sales#index'

  resources :health_insurances, only: [:show, :create, :update] do
    collection do
      get :search
    end
  end

  resources :coinsurances, only: [:show, :create, :update] do
    collection do
      get :search
    end
  end

  resources :pathologies, except: [:show]

  resources :products, except: [] do
    collection do
      get :search
      get :search_for_service
      get :new_batch_update
      post :batch_update
    end
  end

  resources :alfabeta_updates, only: [:index, :show]

  get 'rewards/:id/down_stock', to: 'rewards#down_stock', as: :reward_down_stock
  get 'rewards/:id/up_stock', to: 'rewards#up_stock', as: :reward_up_stock
  post 'rewards/down_stock_update', to: 'rewards#down_stock_update', as: :reward_down_stock_update
  post 'rewards/up_stock_update', to: 'rewards#up_stock_update', as: :reward_up_stock_update
  resources :rewards

  resources :shopping_cart_rewards, except: [:index, :new, :edit, :create, :destroy, :update] do
    get :add_item, on: :member
    get :refresh_item, on: :member
    get :delete_item, on: :member
    get :list, on: :collection
    get :shoping_cart, on: :collection
    post :confirm_shoping_cart, on: :collection
  end

  resources :reward_orders, only: [:index, :show, :destroy] do
    get :change_state, on: :member
    get :voucher_pdf, on: :member
  end

  resources :vademecums do
    get :get_suppliers, on: :member
  end

  resources :supplier_requests, except: [:destroy] do
    member do
      post :add_card
      post :emit
    end
    resources :comments, only: [:create, :index]
  end

  resources :comments, only: [:destroy]

  resources :suppliers do
    get :list_for_map, on: :collection
    get :search, on: :collection
    resources :users do
      resources :sales, except: [:edit, :destroy, :update] do
        resources :sale_products
      end
    end
    resources :supplier_requests do
      collection do
        get :document_form
        post :load_form
      end
    end
    resources :services do
      get :near_expiration, on: :collection
    end
  end

  resources :authorizations, except: [:destroy, :update, :edit, :new]

  resources :sessions, only: :create

  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'admin', to: 'application#admin', as: :admin
  get 'profile', to: 'users#edit', as: :profile

  get 'login', to: 'sessions#login_form', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  get 'no_cards_assigned', to: 'public#no_cards_assigned', as: :no_cards_assigned
  get 'terms_of_use', to: 'public#terms_of_use', as: :terms_of_use
  post 'accept_terms_of_use', to: 'public#accept_terms_of_use', as: :accept_terms_of_use
  root 'public#home'

end

app/models/reward.rb
# == Schema Information
#
# Table name: rewards
#
#  id            :integer          not null, primary key
#  name          :string(255)      not null
#  description   :text(65535)
#  code          :string(255)      not null
#  need_points   :float(24)
#  reward_kind   :string(255)      not null
#  image_uid     :string(255)
#  image_name    :string(255)
#  service_types :text(65535)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Reward < ActiveRecord::Base

  include ActsAsStock
  include ActsAsStockEntry

  dragonfly_accessor :image

  serialize :service_types, Array
  REWARD_KINDS = %w(workshop product other)

  # -- Scopes
  default_scope { order(:code) }

  # -- Validations
  validates :name, :image, :code, :need_points, :reward_kind, presence: true
  validates :name, :code, uniqueness: true

  def to_s
    name
  end

  def stock_entries_arqueo_negativo
    stock_entries.where(codename: 'arqueo_negativo')
  end

  def stock_entries_arqueo_positivo
    stock_entries.where(codename: 'arqueo_positivo')
  end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy, :down_stock, :up_stock, :down_stock_update, :up_stock_update]
  before_action :only_authorize_god!

  def down_stock
    respond_to do |format|
      format.js
    end
  end

  def up_stock
    respond_to do |format|
      format.js
    end
  end


  def down_stock_update
    down_stock = params[:down_stock].to_i
    observation = params[:observation]

    unless down_stock.zero?
      @new_stock_entry = @reward.stock_hard_down({amount: down_stock, owner: @reward, codename: 'arqueo_negativo', observation: observation})
    end

    respond_to do |format|
      flash[:success] = t(:success)
      format.js { render :stock_update }
    end
  end


  def up_stock_update
    up_stock = params[:up_stock].to_i
    observation = params[:observation]

    unless up_stock.zero?
      @new_stock_entry = @reward.stock_hard_up({amount: up_stock, owner: @reward, codename: 'arqueo_positivo', observation: observation})
    end

    respond_to do |format|
      flash[:success] = t(:success)
      format.js { render :stock_update }
    end
  end


  # GET /rewards
  def index
    @filter = RewardFilter.new(filter_params)
    @rewards = @filter.call.page(params[:page])
  end

  # GET /rewards/1
  def show
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards
  def create
    @reward = Reward.new(reward_params)

    respond_to do |format|
      if @reward.save
        format.html { redirect_to rewards_path, notice: 'El premio ha sido creado correctamente.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /rewards/1
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to rewards_path, notice: 'El premio ha sido actualizado correctamente.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /rewards/1
  def destroy
    @reward.destroy
    respond_to do |format|
      format.html { redirect_to rewards_url, notice: 'El premio ha sido eliminado correctamente.' }
    end
  end

  private

  def set_reward
    @reward = Reward.find(params[:id])
  end


  def reward_params
    params['reward']['service_types'] = params['reward']['service_types'] || []
    params['reward']['service_types'] = params['reward']['service_types'].reject(&:blank?)
    params.require(:reward).permit(:name, :description, :code, :need_points, :reward_kind, :image, :remove_image, :service_types => [])
  end

  def filter_params
    if params[:reward_filter]
      params.require(:reward_filter).permit(:name, :code, :need_points, :reward_kind)
    end
  end
end

app/views/rewards/_filter.html.erb
<%= form_for @filter, url: :rewards, method: :get do |f| %>

    <div class="row">
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-3">
            <fieldset class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </fieldset>
          </div>

          <div class="col-md-3">
            <fieldset class="form-group">
              <%= f.label :code %>
              <%= f.text_field :code, class: 'form-control' %>
            </fieldset>
          </div>

          <div class="col-md-3">
            <fieldset class="form-group">
              <%= f.label :need_points %>
              <%= f.text_field :need_points, class: 'form-control' %>
            </fieldset>
          </div>

          <div class="col-md-3">
            <fieldset class="form-group">
              <%= f.label :reward_kind %>
              <%= f.select :reward_kind,
                           Reward::REWARD_KINDS.map { |kind| [t("reward_kinds.#{kind}"), kind] },
                           {include_blank: 'Todos'}, {class: 'form-control'} %>
            </fieldset>
          </div>
        </div>
      </div>

      <div class="col-md-2">
        <fieldset class="form-group">
          <%= f.submit 'Filtrar', class: 'btn btn-primary', style: 'margin-top: 24px;', data: {'disable-with' => 'Cargando...'} %>
        </fieldset>
      </div>
    </div>

<% end %>

app/views/rewards/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <article class="box box-primary">
      <section class="box-body">

        <%= form_for(@reward) do |f| %>
        <% @reward.errors.full_messages.each do |message| %>
        <p><%= message %></p>
        <% end %>


        <div class="row">
          <div class="col-md-6">
            <fieldset class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control', required: true %>
            </fieldset>
          </div>
          <div class="col-md-6">
            <fieldset class="form-group">
              <%= f.label :code %>
              <%= f.text_field :code, class: 'form-control', required: true %>
            </fieldset>
          </div>
          <div class="col-md-6">
            <fieldset class="form-group">
              <%= f.label :need_points %>
              <%= f.number_field :need_points, class: 'form-control', required: true %>
            </fieldset>
          </div>
          <div class="col-md-6">
            <fieldset class="form-group">
              <%= f.label :reward_kind %>
              <%= f.select :reward_kind,
              Reward::REWARD_KINDS.map{|kind| [t("reward_kinds.#{kind}"), kind]},
              {}, {class: 'form-control'} %>
            </fieldset>
          </div>
        </div>

        <fieldset class="form-group">
          <%= f.label :service_types %>
          <%= f.select :service_types,
          Service::TYPES.map{|type| [t("service_types.#{type}"), type]},
          {}, {multiple: :multiple, class: 'form-control select2'} %>
        </fieldset>
        

        <fieldset class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </fieldset>


        <fieldset class="form-group">
          <%= f.label :image %>
          <%= image_tag @reward.image.thumb('100x200').url, class: :thumbnail if @reward.image %>
          <% if @reward.image %>
          <%= f.check_box :remove_image %> <%= f.label :remove_image, 'Remover foto' %>
          <% end %>
          <%= f.file_field :image %>
          <p class="help-block">
            <%= @reward.image ? 'Click para cambiar la foto' : 'Seleccione una fotografía' %>
          </p>
        </fieldset>


        <div class="actions">
          <%= f.submit 'Guardar premio', class: 'btn btn-primary', data: { 'disable-with' => 'Cargando...' } %>
        </div>
        <% end %>

      </section>
    </article>
  </div>


  <% unless @reward.get_stock.nil? %>
    <div class="col-md-6">

      <article class="box box-primary">
        <section class="box-body">
          <div class="row" style="border-bottom: 2px solid #eee; padding-bottom: 10px;">
            <div class="col-xs-6">
              <b>Stock Actual:</b> <span id="real_stock_container"><%= @reward.real_stock.to_i %></span>
            </div>
            <div class="col-xs-6 text-right">
              <b style="margin-right: 8px;">Arqueo Stock</b>
              <a href="javascript:;" class="btn btn-default btn-xs js-down_stock" data-id="<%= @reward.id %>"><i class="text-danger fa fa-minus fa-fw" ></i></a>
              <a href="javascript:;" class="btn btn-default btn-xs js-up_stock" data-id="<%= @reward.id %>"><i class="text-primary fa fa-plus fa-fw" ></i></a>
            </div>
          </div>

        
          <ul id="stock_entries" class="timeline" style="padding-bottom: 15px; padding-top: 15px; margin-bottom: 15px; margin-top: 15px;">
            <%= render partial: "stock_entry", collection: @reward.get_stock.stock_entries.reverse, as: :stock_entry %>
            <li><i class="fa fa-clock-o bg-gray"></i></li>
          </ul>
        </section>
      </article>


    </div>
  <% end %>
</div>

app/views/rewards/_list_filter.html.erb
  <%= form_for @filter, url: list_rewards_path, method: :get do |f| %>

  <div class="row">

    <div class="col-md-10">

      <div class="row">

        <div class="col-md-3">
          <fieldset class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </fieldset>
        </div>

        <div class="col-md-3">
          <fieldset class="form-group">
            <%= f.label :code %>
            <%= f.text_field :code, class: 'form-control' %>
          </fieldset>
        </div>

        <div class="col-md-3">
          <fieldset class="form-group">
            <%= f.label :need_points %>
            <%= f.text_field :need_points, class: 'form-control' %>
          </fieldset>
        </div>

        <div class="col-md-3">
          <fieldset class="form-group">
            <%= f.label :reward_kind %>
            <%= f.select :reward_kind,
              Reward::REWARD_KINDS.map{|kind| [t("reward_kinds.#{kind}"), kind]},
              {include_blank: 'Todos'}, {class: 'form-control'} %>
          </fieldset>
        </div>

      </div>

    </div>



    <div class="col-md-2">
      <fieldset class="form-group">
        <%= f.submit 'Filtrar', class: 'btn btn-primary', style: "margin-top: 24px;", data: { 'disable-with' => 'Cargando...'} %>
      </fieldset>
    </div>
  </div>

  <% end %>

app/views/rewards/_modal_down_stock.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h3 class="modal-title">

		<i class="fa fa-fw fa-gift"></i> <%= @reward %> <small>Decremento de Stock</small>

	</h3>
</div>

<%= form_tag reward_down_stock_update_path, {remote: true, html: {class: 'down_stock_form'}} do |f| %>
<div class="modal-body">
	
	<%= hidden_field_tag :id, @reward.id  %>

	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label class="control-label">Decremento de Stock</label>
				<%= number_field_tag :down_stock, 0, step: 0.01, class: 'form-control' %>
			</div>
		</div>
		<div class="col-md-6">
			<label class="control-label">Stock Total</label>
			<div class="input-group ">
				<p class="form-control-static"><%= @reward.real_stock.to_i %></p>
			</div>
		</div>

		<div class="col-md-12">
			<label class="control-label">Observación</label>
			<%= text_area_tag :observation, '', class: 'form-control' %>
		</div>

	</div>

</div>

<div class="modal-footer">
	<div class="actions">
		<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
		<%= button_tag('Guardar', type: 'submit', class: "btn btn-success btn-ok", data: {'disable-with' => 'Guardando'}) %>
	</div>
</div>

<% end %>

app/views/rewards/_modal_up_stock.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h3 class="modal-title">

		<i class="fa fa-fw fa-gift"></i> <%= @reward %> <small>Incremento de Stock</small>

	</h3>
</div>

<%= form_tag reward_up_stock_update_path, {remote: true, html: {class: 'up_stock_form'}} do |f| %>
<div class="modal-body">
	
	<%= hidden_field_tag :id, @reward.id  %>


	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label class="control-label">Incremento de Stock</label>
				<%= number_field_tag :up_stock, 0, step: 0.01, class: 'form-control' %>
			</div>
		</div>
		<div class="col-md-6">
			<label class="control-label">Stock Total</label>
			<div class="input-group ">
				<p class="form-control-static"><%= @reward.real_stock.to_i %></p>
			</div>
		</div>

		<div class="col-md-12">
			<label class="control-label">Observación</label>
			<%= text_area_tag :observation, '', class: 'form-control' %>
		</div>
	</div>

</div>

<div class="modal-footer">
	<div class="actions">
		<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
		<%= button_tag('Guardar', type: 'submit', class: "btn btn-success btn-ok", data: {'disable-with' => 'Guardando'}) %>
	</div>
</div>

<% end %>

app/views/rewards/_reward.html.erb
<tr>
  <td><%= image_tag reward.image.thumb('100x200').url %></td>
  <td><%= reward.code %></td>
  <td><%= reward.name %></td>
  <td><%= reward.need_points %></td>
  <td><%= reward.real_stock.to_i %></td>
  <td><%= t reward.reward_kind, scope: :reward_kinds %></td>  
  <td><%= reward.service_types.map{|x| t(x, scope: :service_types) }.join('<br/>').html_safe %></td>
  <td class="pull-right">
    <%= link_to 'Editar', edit_reward_path(reward), class: 'btn btn-xs btn-success' %>
    <%= link_to 'Eliminar', reward, method: :delete, data: {confirm: '¿Está seguro?'}, class: 'btn btn-xs btn-danger' %>
  </td>
</tr>

app/views/rewards/_reward_shop_cart_control.html.erb
<% item = ShopCart::find(session, reward.id) %>
<% if item.nil? %>

	<div class="col-xs-12 text-right">
		<%= link_to add_item_reward_path(reward, source: source), remote: true do %>
		<i class="fa fa-2x fa-cart-plus"></i>
		<% end %>
	</div>

<% else %>

		<div class="col-xs-6">
			<% if source == 'list' %>
				<a class="btn btn-success disabled" href="#">x<%= item['amount'] %></a>
			<% end %>
		</div>
		<div class="col-xs-6 text-right">
			<%= link_to refresh_item_reward_path(reward, source: source, act: 'inc'), remote: true do %>
			<i class="fa fa-2x fa-plus-circle"></i>
			<% end %>

			<% if item['amount'] > 1 %>
				<%= link_to refresh_item_reward_path(reward, source: source, act: 'dec'), remote: true do %>
				<i class="fa fa-2x fa-minus-circle"></i>
				<% end %>
			<% else %>
				<%= link_to refresh_item_reward_path(reward, source: source, act: 'dec'), style: 'visibility: hidden;', remote: true do %>
				<i class="fa fa-2x fa-minus-circle"></i>
				<% end %>
			<% end %>
			<%= link_to delete_item_reward_path(reward, source: source), remote: true do %>
			<i class="fa fa-2x fa-trash"></i>
			<% end %>						
		</div>

<% end %>

app/views/rewards/_stock_entry.html.erb
<li>
<% case stock_entry.codename %>
<% when 'arqueo_negativo' %>
  <i class="fa fa-minus bg-red"></i>
<% when 'arqueo_positivo' %>
  <i class="fa fa-plus bg-blue"></i>
<% when 'canjeo_premio' %>
  <i class="fa fa-gift bg-green"></i>
<% when 'cancelado_premio' %>
  <i class="fa fa-gift bg-yellow"></i>      
<% end %>


  <div class="timeline-item">

    <span class="time"><i class="fa fa-calendar-o"></i> <%= stock_entry.created_at.strftime("%d/%m/%Y %T") %></span>

    <h3 class="timeline-header text-left">
    	<%= t stock_entry.codename, scope: 'stock_entry_codenames' %>
    	<span class="badge"><%= stock_entry.amount.to_i %></span>
    </h3>

    <div class="timeline-body">

    <% if ['canjeo_premio', 'cancelado_premio'].include?(stock_entry.codename) %>
    	<% reward_order = stock_entry.owner.reward_order %>
      <%= link_to "Voucher #{reward_order.code}", reward_order, class: '', target: '_blank' %>
    <% else %>
      <%= stock_entry.observation %>
    <% end %>

    </div>
  </div>
</li>

app/views/rewards/delete_item.js.erb
<% if @source == 'list' %>
$('#reward_shop_cart_control_container_<%= @reward.id %>').html('<%= j render 'reward_shop_cart_control', reward: @reward, source: @source %>');
<% elsif @source == 'cart' %>
$('#reward_shop_cart_control_container_<%= @reward.id %>').parent().fadeOut(function() { $(this).remove(); });
<% end %>
$('#shopping-cart-snippet').replaceWith('<%= j render 'shopping_cart_snippet' %>');

app/views/rewards/down_stock.js.erb
$('#modal_one .modal-dialog');
$('#modal_one .modal-content').html('<%= j render 'modal_down_stock' %>');

app/views/rewards/edit.html.erb
<header class="content-header">
  <%# link_to 'Ver', @reward,
      class: 'btn btn-primary pull-right' %>
	<%= link_to 'Volver', rewards_path,
      class: 'btn btn-default pull-right' %>      
  <h1>Editar Premio</h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>

app/views/rewards/index.html.erb
<header class="content-header">
  <%= link_to 'Nuevo Premio', new_reward_path,
      class: 'btn btn-primary pull-right' %>
  <h1>Premios</h1>
</header>

<!-- Main content -->
<section class="content">
<article class="box box-primary">
<section class="box-body">

  <%= render 'filter' %>

  <table class="table vertical-align-middle">
    <thead>
      <tr>
        <th>Imagen</th>
        <th>Código</th>
        <th>Nombre</th>
        <th>Puntos</th>
        <th>Stock</th>
        <th>Tipo</th>
        <th>Aplica</th>
        <th></th>
      </tr>
    </thead>
  
    <tbody>
      <%= render @rewards %>
    </tbody>
  </table>

  <%= paginate @rewards %>

</section>
</article>
</section>

app/views/rewards/new.html.erb
<header class="content-header">
  <%= link_to 'Volver', rewards_path,
      class: 'btn btn-default pull-right' %>
  <h1>Nuevo Premio</h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>

app/views/rewards/shoping_cart.html.erb
<header class="content-header">
	<h1>Premios Seleccionados</h1>
</header>

<section class="content">

	<article class="box box-primary">
		<section class="box-body">





			<% if current_shop_cart.size != 0 %>

			<%= form_for(@reward_order, url: confirm_shoping_cart_rewards_path) do |f| %>
			<% @reward_order.errors.full_messages.each do |message| %>
			<p><%= message %></p>
			<% end %>

			<%= f.hidden_field :user_id %>


			<div class="row">
			  <fieldset class="form-group col-md-5">
			    <%= f.label :supplier_id %>
					<%= f.collection_select :supplier_id, Supplier.all, :id, :name, {}, {class: 'form-control'} %>
			  </fieldset>
			</div>

			<hr>

			<table class="table table-striped vertical-align-middle" id="shop_cart_item_table">
				<thead>
					<tr>
						<th colspan="2">Premio</th>
						<th class="text-center">Puntos</th>
						<th class="text-center">Cantidad</th>
						<th class="text-center">Subtotal</th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody id="products">
					<% total_amount = 0 %>
					<% total_need_points_subtotal = 0 %>

					<% current_shop_cart.each do |item| %>
					<% reward = Reward.find(item['item_id']) %>
					<% need_points_subtotal = reward.need_points * item['amount'] %>
					<tr class="tr-link shop_cart_item">
						<td><%= image_tag reward.image.thumb('100x200').url, class: 'img-thumbnail' %></td>
						<td class="white-space-nowrap"><%= reward.name %></td>
						<td class="text-center"><%= reward.need_points %></td>
						<td class="text-center reward_amount_container" id="reward_amount_container_<%= reward.id %>"><%= item['amount'] %></td>
						<td class="text-center reward_need_points_subtotal_container" id="reward_need_points_subtotal_container_<%= reward.id %>"><%= need_points_subtotal %></td>
						<td class="reward_shop_cart_control" id="reward_shop_cart_control_container_<%= reward.id %>">
							<%= render 'reward_shop_cart_control', reward: reward, source: 'cart' %>
						</td>
					</tr>
					<% total_amount += item['amount']  %>
					<% total_need_points_subtotal += need_points_subtotal  %>
					<% end %>



					<tr class="totales success">
						<td colspan="3"><h3 style="margin-top: 10px;">Totales</h3></td>
						<td class="text-center"><h3 style="margin-top: 10px;" id="total_amount"><%= total_amount %></h3></td>
						<td class="text-center"><h3 style="margin-top: 10px;" id="total_need_points_subtotal"><%= total_need_points_subtotal %></h3></td>
						<td class="text-right">
							<%= f.submit 'Confirmar', class: 'btn btn-lg btn-primary', data: { 'disable-with' => 'Confirmando...' } %>
						</td>
					</tr>
				</tbody>
			</table>



			<% end %>




			<% elsif current_shop_cart.size == 0 %>

			<h3>Sin productos Agregados</h3>

			<% end %>



		</section>
	</article>
</section>