config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :cards, only: :create
    resources :sales, only: :update do
      post :authorize, on: :collection
      post :confirm, on: :collection
    end
  end

  resources :users do
    collection do
      get :search
    end
    member do
      patch :assign_card
      get :edit_points
      put :update_points
    end
    resources :services, except: [:index] do
      put :activate, on: :member
      put :finalize, on: :member
    end
    resources :sales, except: [:edit, :destroy, :update] do
      resources :sale_products
    end
  end

  resources :laboratories, only: [] do
    get :search, on: :collection
  end

  resources :drugs, only: [] do
    get :search, on: :collection
  end

  resources :services, only: [] do
    get :near_expiration, on: :collection
    get :history, on: :member
  end

  get 'my_purchases', to: 'sales#index'

  resources :health_insurances, only: [:show, :create, :update] do
    collection do
      get :search
    end
  end

  resources :coinsurances, only: [:show, :create, :update] do
    collection do
      get :search
    end
  end

  resources :pathologies, except: [:show]

  resources :products, except: [] do
    collection do
      get :search
      get :search_for_service
      get :new_batch_update
      post :batch_update
    end
  end

  resources :alfabeta_updates, only: [:index, :show]

  get 'rewards/:id/down_stock', to: 'rewards#down_stock', as: :reward_down_stock
  get 'rewards/:id/up_stock', to: 'rewards#up_stock', as: :reward_up_stock
  post 'rewards/down_stock_update', to: 'rewards#down_stock_update', as: :reward_down_stock_update
  post 'rewards/up_stock_update', to: 'rewards#up_stock_update', as: :reward_up_stock_update
  resources :rewards

  resources :shopping_cart_rewards, except: [:index, :new, :edit, :create, :destroy, :update] do
    get :add_item, on: :member
    get :refresh_item, on: :member
    get :delete_item, on: :member
    get :list, on: :collection
    get :shoping_cart, on: :collection
    post :confirm_shoping_cart, on: :collection
  end

  resources :reward_orders, only: [:index, :show, :destroy] do
    get :change_state, on: :member
    get :voucher_pdf, on: :member
  end

  resources :vademecums do
    get :get_suppliers, on: :member
  end

  resources :supplier_requests, except: [:destroy] do
    member do
      post :add_card
      post :emit
    end
    resources :comments, only: [:create, :index]
  end

  resources :comments, only: [:destroy]

  resources :suppliers do
    get :list_for_map, on: :collection
    get :search, on: :collection
    resources :users do
      resources :sales, except: [:edit, :destroy, :update] do
        resources :sale_products
      end
    end
    resources :supplier_requests do
      collection do
        get :document_form
        post :load_form
      end
    end
    resources :services do
      get :near_expiration, on: :collection
    end
  end

  resources :authorizations, except: [:destroy, :update, :edit, :new]

  resources :sessions, only: :create

  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'admin', to: 'application#admin', as: :admin
  get 'profile', to: 'users#edit', as: :profile

  get 'login', to: 'sessions#login_form', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  get 'no_cards_assigned', to: 'public#no_cards_assigned', as: :no_cards_assigned
  get 'terms_of_use', to: 'public#terms_of_use', as: :terms_of_use
  post 'accept_terms_of_use', to: 'public#accept_terms_of_use', as: :accept_terms_of_use
  root 'public#home'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                         :integer          not null, primary key
#  code                       :string(255)      not null
#  barcode                    :string(255)
#  troquel_number             :string(255)
#  name                       :string(255)      not null
#  presentation_form          :string(255)
#  price_in_cents             :float(24)
#  registration_number        :integer
#  units                      :integer          default(1)
#  size                       :integer
#  client_points              :float(24)        default(0.0)
#  seller_points              :float(24)        default(0.0)
#  drug_id                    :integer
#  laboratory_id              :integer
#  deleted                    :boolean          default(FALSE)
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#

class Product < ActiveRecord::Base

  # -- Callbacks
  after_create :initialize_points, if: Proc.new { |u| u.client_points.nil? }

  # -- Associations
  has_many :supplier_point_products
  has_many :price_histories
  accepts_nested_attributes_for :supplier_point_products, allow_destroy: true
  belongs_to :drug
  belongs_to :laboratory

  # -- Validations
  validates :name, :alfabeta_identifier, presence: true

  # -- Scopes
  default_scope { order(:name) }
  scope :search, ->(q) { joins(:drug).where('products.name LIKE :a OR products.barcode LIKE :a OR products.troquel_number LIKE :a OR drugs.name LIKE :a OR products.presentation_form LIKE :a', a: "%#{q}%") }

  # -- Methods
  def self.products_for_service(params_vademecum, user)
    pfpc_services = user.pfpc_services.available
    products_in_services = pfpc_services.joins(:product_pfpcs)
    product_ids = products_in_services.pluck(:product_id)

    if params_vademecum
      products = Vademecum.find(params_vademecum).products.where.not(id: product_ids)
    else
      products = Product.all
    end

    products
  end

  def self.points_batch_update(client_points, seller_points, laboratory_id)
    products = (laboratory_id.present?) ? Product.where(laboratory_id: laboratory_id) : Product.all
    products.update_all(client_points: client_points) unless client_points.blank?
    products.update_all(seller_points: seller_points) unless seller_points.blank?
  end

  def to_s
    s = "#{name}"
    s += ", #{presentation_form}" unless presentation_form.nil?
    s
  end

  def price
    price_in_cents.to_d / 100 if price_in_cents
  end

  def initialize_points
    self.update(client_points: 0)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :only_authorize_god!, only: [:index, :new, :create, :destroy, :edit]


  # GET /products
  def index
    @filter = ProductFilter.new(filter_params)
    @products = @filter.call.page(params[:page])
  end


  # GET /products/new
  def new
    @product = Product.new
  end


  # GET /products/1/edit
  def edit
  end

  # GET /products/1
  def show
  end

  # POST /products
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'El producto ha sido creado correctamente.' }
      else
        format.html { render :new }
      end
    end
  end


  # PATCH/PUT /products/1
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: "El producto #{@product} ha sido actualizado correctamente." }
      else
        format.html { render :edit }
      end
    end
  end


  # DELETE /products/1
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'El producto ha sido eliminado correctamente.' }
    end
  end


  def new_batch_update
  end


  def batch_update
    Product.points_batch_update(params[:client_points], params[:seller_points], params[:laboratory_id])
    redirect_to products_path, notice: 'Se han actualizado los productos'
  end


  # GET /products/search
  def search
    block = lambda { |record| {
        id: record.id,
        name: record.name,
        price: record.price,
        laboratory: record.laboratory.to_s,
        barcode: record.barcode || '-',
        troquel_number: record.troquel_number || '-',
        presentation_form: record.presentation_form,
        alfabeta_identifier: record.alfabeta_identifier,
        drug: record.drug.blank? ? 'NA' : record.drug.name,
        extra: "<div class='row'>
                  <div class='col-md-6'>
                    <dl>
                      <dt>Presentación</dt>
                      <dd>#{record.presentation_form}</dd>
                      <dt>Monodroga</dt>
                      <dd>#{record.drug.blank? ? 'NA' : record.drug.name}</dd>
                    </dl>
                  </div>
                  <div class='col-md-6'>
                    <dl>
                      <dt>Laboratorio</dt>
                      <dd>#{record.laboratory.name}</dd>
                      <dt>Código de barra</dt>
                      <dd>#{record.barcode}</dd>
                    </dl>
                  </div>
                </div>"
    } }
    records = RecordSearcher.call(Product.all.includes(:laboratory, :drug).references(:drug), params, &block)
    render json: records.to_json, callback: params[:callback]
  end


  # GET /products/search_for_service.json
  # Retorna los productos que no están en ningún servicio del usuario (params[:user_id])
  # que cumplen con la búsqueda
  def search_for_service
    block = lambda { |record| {
        id: record.id,
        name: record.name,
        price: record.price,
        laboratory: record.laboratory.to_s,
        barcode: record.barcode || '-',
        troquel_number: record.troquel_number || '-',
        presentation_form: record.presentation_form,
        alfabeta_identifier: record.alfabeta_identifier,
        drug: record.drug.blank? ? 'NA' : record.drug.name,
        extra: "<div class='row'>
                  <div class='col-md-6'>
                    <dl>
                      <dt>Presentación</dt>
                      <dd>#{record.presentation_form}</dd>
                      <dt>Monodroga</dt>
                      <dd>#{record.drug.blank? ? 'NA' : record.drug.name}</dd>
                    </dl>
                  </div>
                  <div class='col-md-6'>
                    <dl>
                      <dt>Laboratorio</dt>
                      <dd>#{record.laboratory.name}</dd>
                      <dt>Código de barra</dt>
                      <dd>#{record.barcode}</dd>
                    </dl>
                  </div>
                </div>"
    } }

    user = User.find(params[:user_id])
    products_for_search = Product.includes(:laboratory, :drug).products_for_service(params[:vademecum_id], user)
    records = RecordSearcher.call(products_for_search, params, &block)
    render json: records.to_json, callback: params[:callback]
  end


  private

  def set_product
    @product = Product.find(params[:id])
  end


  def product_params
    params.require(:product).permit(:name, :code, :barcode, :troquel_number, :client_points, :seller_points,
                                    supplier_point_products_attributes: [:id, :client_points, :seller_points, :supplier_id, :_destroy])
  end


  def filter_params
    if params[:product_filter]
      params.require(:product_filter).permit(:name, :laboratory_id, :drug_id)
    end
  end

end

app/views/products/_filter.html.erb
<%= form_for @filter, url: :products, method: :get do |f| %>

  <div class="row">
    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </fieldset>
    </div>
    
    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.label :laboratory_id %>
        <%= f.hidden_field :laboratory_id, class: 'select2',
              data: { behavior: 'searchLaboratory', url: search_laboratories_path, 'record-id' => @filter.laboratory_id, 'record-text' => @filter.laboratory_name } %>
      </fieldset>
    </div>
    
    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.label :drug_id %>
        <%= f.hidden_field :drug_id, class: 'select2',
              data: { behavior: 'searchDrug', url: search_drugs_path, 'record-id' => @filter.drug_id, 'record-text' => @filter.drug_name } %>
      </fieldset>
    </div>

    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.label :filter %><br />
        <%= f.submit 'Filtrar', class: 'btn btn-primary',
            data: { 'disable-with' => 'Cargando...'} %>
      </fieldset>
    </div>
  </div>

<% end %>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-9">
    <article class="box box-primary">
      <section class="box-body">

        <%= form_for(@product) do |f| %>
            <% @product.errors.full_messages.each do |message| %>
                <p><%= message %></p>
            <% end %>

            <fieldset class="form-group">
              <%= f.label :barcode %>
              <%= f.text_field :barcode, class: 'form-control', required: true %>
            </fieldset>

            <fieldset class="form-group">
              <%= f.label :troquel_number %>
              <%= f.text_field :troquel_number, class: 'form-control', required: true %>
            </fieldset>

            <fieldset class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control', required: true %>
            </fieldset>

            <fieldset class="form-group">
              <%= f.label :presentation_form %>
              <%= f.text_field :presentation_form, class: 'form-control' %>
            </fieldset>

            <div class="row">
              <fieldset class="form-group col-md-4">
                <%= f.label :client_points %>
                <%= f.text_field :client_points, class: 'form-control', required: true %>
              </fieldset>
              <fieldset class="form-group col-md-4">
                <%= f.label :seller_points %>
                <%= f.text_field :seller_points, class: 'form-control', required: true %>
              </fieldset>
            </div>

            <div class="row">
              <div class="col-md-4"> <%= label_tag :supplier_point_products, 'Prestador' %> </div>
              <div class="col-md-3"> <%= label_tag :supplier_point_products, '% de puntos cliente' %> </div>
              <div class="col-md-3"> <%= label_tag :supplier_point_products, '% de puntos vendedor' %> </div>
            </div>

            <div class="supplier_point_products form-group">
              <%= f.fields_for :supplier_point_products do |p| %>
                  <%= render 'supplier_point_product_fields', f: p %>
              <% end %>
              <div class="links">
                <%= link_to_add_association 'Nuevo', f, :supplier_point_products, class: 'btn btn-default' %>
              </div>
            </div>

            <div class="actions">
              <%= f.submit 'Guardar producto', class: 'btn btn-primary', data: {'disable-with' => 'Cargando...'} %>
            </div>
        <% end %>

      </section>
    </article>
  </div>
  <div class="col-md-3">

    <div class="callout callout-warning">
      <h4>Notas</h4>

      <p>Recuerde que los <b>Puntos</b> especificados funcionan a nivel global y que luego puede crear puntos
        específicos para un prestador determinado.</p>
    </div>

  </div>
</div>

app/views/products/_product.html.erb
<tr>
  <td> <%= product %> </td>
  <td> <%= product.laboratory %> </td>
  <td> <%= number_to_currency product.price %> </td>
  <td> <%= product.drug %> </td>
  <td> <%= product.client_points %> </td>
  <td> <%= product.seller_points %> </td>
  <td class="pull-right">
    <%= link_to 'Ver', product, method: :get, class: 'btn btn-xs btn-info' %>
    <%= link_to 'Editar', edit_product_path(product), class: 'btn btn-xs btn-success' %>
    <%= link_to 'Eliminar', product, method: :delete,
        data: {confirm: '¿Está seguro?'}, class: 'btn btn-xs btn-danger' %>
  </td>
</tr>

app/views/products/_show_product.html.erb
<div class="row">
  <div class="col-md-9">
    <article class="box box-primary">
      <section class="box-body">
        <%= form_for(@product) do |f| %>
            <% @product.errors.full_messages.each do |message| %>
                <p><%= message %></p>
            <% end %>

            <fieldset class="form-group">
              <%= f.label :barcode %>
              <%= f.text_field :barcode, class: 'form-control', disabled: true %>
            </fieldset>

            <fieldset class="form-group">
              <%= f.label :troquel_number %>
              <%= f.text_field :troquel_number, class: 'form-control', disabled: true %>
            </fieldset>

            <fieldset class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control', disabled: true %>
            </fieldset>

            <fieldset class="form-group">
              <%= f.label :presentation_form %>
              <%= f.text_field :presentation_form, class: 'form-control', disabled: true  %>
            </fieldset>

            <div class="row">
              <fieldset class="form-group col-md-4">
                <%= f.label :client_points %>
                <%= f.text_field :client_points, class: 'form-control', disabled: true %>
              </fieldset>
              <fieldset class="form-group col-md-4">
                <%= f.label :seller_points %>
                <%= f.text_field :seller_points, class: 'form-control', disabled: true %>
              </fieldset>
            </div>
            <%= link_to 'Editar', edit_product_path(@product), class: 'btn btn-xs btn-success' %>
            <%= link_to 'Eliminar', @product, method: :delete, data: {confirm: '¿Está seguro?'}, class: 'btn btn-xs btn-danger' %>      
        <% end %>
      </section>
      
    </article>
  </div>
</div>

app/views/products/_supplier_point_product_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-md-4">
      <fieldset class="form-group">
        <%= f.collection_select :supplier_id, Supplier.all, :id, :to_s, {include_blank: '-- Prestador --'}, {class: 'form-control'} %>
      </fieldset>
    </div>
    
    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.text_field :client_points, class: 'form-control', required: true, placeholder: '% de puntos' %>
      </fieldset>
    </div>
    
    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.text_field :seller_points, class: 'form-control', required: true, placeholder: '% de puntos' %>
      </fieldset>
    </div>
    
    <div class="col-md-1">
      <fieldset class="form-group">
        <%= link_to_remove_association "eliminar", f, class: 'btn btn-danger' %>
      </fieldset>
    </div>
    
  </div>
</div>

app/views/products/edit.html.erb
<header class="content-header">
  <h1>Editar Producto</h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>

app/views/products/index.html.erb
<header class="content-header">
  <div class="pull-right">
    <%= link_to 'Actualización masiva', new_batch_update_products_path,
                class: 'btn btn-warning' %>
    <%#= link_to 'Nuevo Producto', new_product_path,
                class: 'btn btn-primary' %>
  </div>
  <h1>Productos</h1>
</header>

<!-- Main content -->
<section class="content">
  <article class="box box-primary">
    <section class="box-body">

      <%= render 'filter' %>

      <table class="table">
        <thead>
        <tr>
          <th>Nombre</th>
          <th>Laboratorio</th>
          <th>Precio Sugerido</th>
          <th>Monodroga</th>
          <th>Puntos comprador</th>
          <th>Puntos vendedor</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <%= render @products %>
        </tbody>
      </table>

      <%= paginate @products %>

    </section>
  </article>
</section>

app/views/products/new.html.erb
<header class="content-header">
  <%= link_to 'Volver', products_path,
      class: 'btn btn-default pull-right' %>
  <h1>Nuevo Producto</h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>

app/views/products/new_batch_update.html.erb
<header class="content-header">
  <%= link_to 'Volver', products_path,
              class: 'btn btn-default pull-right' %>
  <h1>Actualización Masiva</h1>
</header>

<section class="content">
  <div class="row">
    <div class="col-md-9">
      <article class="box box-primary">
        <section class="box-body">

          <%= form_tag batch_update_products_path, method: :post do |f| %>

              <div class="row">
                <fieldset class="form-group col-md-2">
                  <%= label_tag :client_points, 'Puntos compradores' %>
                  <%= text_field_tag :client_points, '', class: 'form-control' %>
                </fieldset>

                <fieldset class="form-group col-md-2">
                  <%= label_tag :seller_points, 'Puntos vendedores' %>
                  <%= text_field_tag :seller_points, '', class: 'form-control' %>
                </fieldset>

                <fieldset class="form-group col-md-8">
                  <%= label_tag :laboratory_id, 'Laboratorio' %>
                  <%= hidden_field_tag :laboratory_id, '', class: 'select2',
                                       data: {behavior: 'searchLaboratory', url: search_laboratories_path} %>
                </fieldset>

              </div>

              <div class="actions">
                <%= submit_tag 'Actualizar', class: 'btn btn-primary', data: {'disable-with' => 'Actualizando...'} %>
              </div>
          <% end %>

        </section>
      </article>
    </div>
    <div class="col-md-3">
      <div class="callout callout-warning">
        <h4>Notas</h4>
        <p>Deje el campo puntos <b>compradores</b> o <b>vendedores</b> en blanco para no actualizarlos.</p>
        <p>Deje el campo <b>Laboratorio</b> en blanco si desea actualizar todos los productos.</p>
      </div>
    </div>

  </div>
</section>

app/views/products/show.html.erb
<header class="content-header">
  <%= link_to 'Volver', products_path, class: 'btn btn-default pull-right' %>
  <h1>Producto</h1>
</header>

<section class="content">
  <%= render 'show_product' %>

  <% unless @product.price_histories.empty? %>
      <div class="row">
        <div class="col-md-9">
          <article class="box box-primary">
            <section class="box-header">
              <h5>Historial de precios</h5>
            </section>
            <section class="box-body">
              <table class="table">
                <thead>
                <tr>
                  <th>Fecha</th>
                  <th>Identificador Alfabeta</th>
                  <th>Precio</th>
                </tr>
                </thead>

                <tbody>
                <% @product.price_histories.each do |price| %>
                    <tr>
                      <td> <%= price.created_at.strftime('%d/%m/%Y - %T') %> </td>
                      <td> <%= price.alfabeta_update_id %> </td>
                      <td> <%= number_to_currency price.price %> </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </section>
          </article>
        </div>
      </div>
  <% end %>
</section>