config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :cards, only: :create
    resources :sales, only: :update do
      post :authorize, on: :collection
      post :confirm, on: :collection
    end
  end

  resources :users do
    collection do
      get :search
    end
    member do
      patch :assign_card
      get :edit_points
      put :update_points
    end
    resources :services, except: [:index] do
      put :activate, on: :member
      put :finalize, on: :member
    end
    resources :sales, except: [:edit, :destroy, :update] do
      resources :sale_products
    end
  end

  resources :laboratories, only: [] do
    get :search, on: :collection
  end

  resources :drugs, only: [] do
    get :search, on: :collection
  end

  resources :services, only: [] do
    get :near_expiration, on: :collection
    get :history, on: :member
  end

  get 'my_purchases', to: 'sales#index'

  resources :health_insurances, only: [:show, :create, :update] do
    collection do
      get :search
    end
  end

  resources :coinsurances, only: [:show, :create, :update] do
    collection do
      get :search
    end
  end

  resources :pathologies, except: [:show]

  resources :products, except: [] do
    collection do
      get :search
      get :search_for_service
      get :new_batch_update
      post :batch_update
    end
  end

  resources :alfabeta_updates, only: [:index, :show]

  get 'rewards/:id/down_stock', to: 'rewards#down_stock', as: :reward_down_stock
  get 'rewards/:id/up_stock', to: 'rewards#up_stock', as: :reward_up_stock
  post 'rewards/down_stock_update', to: 'rewards#down_stock_update', as: :reward_down_stock_update
  post 'rewards/up_stock_update', to: 'rewards#up_stock_update', as: :reward_up_stock_update
  resources :rewards

  resources :shopping_cart_rewards, except: [:index, :new, :edit, :create, :destroy, :update] do
    get :add_item, on: :member
    get :refresh_item, on: :member
    get :delete_item, on: :member
    get :list, on: :collection
    get :shoping_cart, on: :collection
    post :confirm_shoping_cart, on: :collection
  end

  resources :reward_orders, only: [:index, :show, :destroy] do
    get :change_state, on: :member
    get :voucher_pdf, on: :member
  end

  resources :vademecums do
    get :get_suppliers, on: :member
  end

  resources :supplier_requests, except: [:destroy] do
    member do
      post :add_card
      post :emit
    end
    resources :comments, only: [:create, :index]
  end

  resources :comments, only: [:destroy]

  resources :suppliers do
    get :list_for_map, on: :collection
    get :search, on: :collection
    resources :users do
      resources :sales, except: [:edit, :destroy, :update] do
        resources :sale_products
      end
    end
    resources :supplier_requests do
      collection do
        get :document_form
        post :load_form
      end
    end
    resources :services do
      get :near_expiration, on: :collection
    end
  end

  resources :authorizations, except: [:destroy, :update, :edit, :new]

  resources :sessions, only: :create

  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'admin', to: 'application#admin', as: :admin
  get 'profile', to: 'users#edit', as: :profile

  get 'login', to: 'sessions#login_form', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  get 'no_cards_assigned', to: 'public#no_cards_assigned', as: :no_cards_assigned
  get 'terms_of_use', to: 'public#terms_of_use', as: :terms_of_use
  post 'accept_terms_of_use', to: 'public#accept_terms_of_use', as: :accept_terms_of_use
  root 'public#home'

end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id                  :integer          not null, primary key
#  seller_id           :integer
#  client_id           :integer
#  client_points       :float(24)        default(0.0)
#  seller_points       :float(24)        default(0.0)
#  total               :float(24)        default(0.0)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  health_insurance_id :integer
#  coinsurance_id      :integer
#  authorization_id    :integer
#

class Sale < ActiveRecord::Base

  # -- Callbacks
  after_create :send_mail_to_gods, if: :price_greater_than_pvs?

  # -- Scopes
  default_scope -> { order('created_at DESC') }
  scope :all_from_seller, ->(user) { where(seller_id: user) }
  scope :all_from_client, ->(user) { where(client_id: user) }

  # -- Associations
  has_many :sale_products, dependent: :destroy
  accepts_nested_attributes_for :sale_products, allow_destroy: true
  belongs_to :seller, class_name: 'User', foreign_key: 'seller_id'
  belongs_to :client, class_name: 'User', foreign_key: 'client_id'
  has_one :supplier, through: :seller
  belongs_to :authorization

  # -- Callbacks
  after_save :update_services

  # -- Validations
  validates :seller, presence: true
  validates :client, presence: true

  # -- Methods
  def price_greater_than_pvs?
    greater = false
    sale_products.map do |sp|
      if sp.cost > Product.find(sp.product_id).price
        greater = true
      end
    end
    greater
  end

  def send_mail_to_gods
    # TODO activar
    # title = 'Han vendido un producto con costo mayor al PVS'
    # message = 'Para verla, haga clic en el siguiente botón e ingrese con su usuario y contraseña. '
    # User.with_role('god').map do |god|
    #   url = "/users/#{god.id}/sales/#{id}"
    #   UserMailer.new_mail(god, title, message, 'Nueva venta con costo mayor a pvs', url)
    # end
  end

  def total
    sale_products.reduce(0) { |sum, sale_product| sum + sale_product.total }
  end

  def self.all_from_supplier(supplier_id)
    self.joins(:supplier).where(:suppliers => {id: supplier_id})
  end

  def self.between_dates(start_date, finish_date)
    self.where('date(sales.created_at) BETWEEN ? AND ?', start_date.to_date, finish_date.to_date)
  end

  def update_services
    #Acá se van a ir llamando todos los callbacks como actualizar periodo, actualizar puntos, etc
    update_periods
    update_client_points
    update_seller_points
  end

  def update_periods
    id_with_amounts = get_total_amounts(sale_products)
    id_with_amounts.each_pair do |id, amount|
      product = Product.find(id)
      period = PeriodProduct.find_period(client, product)
      if period.present? && client.has_supplier?(seller.supplier)
        period.add_to_accumulated(amount)
      end
    end
  end

  def get_total_amounts(sale_products)
    id_with_sales = sale_products.group_by { |sp| sp.product_id }
    totals = {}
    id_with_sales.each do |id, sales_array|
      id_total = sales_array.reduce(0) { |sum, sa| sum + sa.amount }
      totals[id] = id_total
    end
    totals
  end

  def update_client_points
    # si servicio_puntos está activo
    # actualizar ultimo periodo
    if client.has_points_service?
      period = client.points_services.first.last_period
      accumulated_points = client_points
      period.update_accumulated(accumulated_points)
    end
  end

  def update_seller_points
    if seller.has_seller_service?
      seller.cache_points += seller_points
      seller.save!
    end
  end

end

app/controllers/api/sales_controller.rb
class Api::SalesController < Api::MainController

  def authorize
    adapter = AuthorizationAdapter.new(query)
    if adapter.valid_input?
      manager = AuthorizationFromSale.new(adapter.sale, adapter.seller, adapter.query[:ticket], adapter.response)
      authorization = manager.authorize!
      # TODO mejorar
      render json: {status: :ok, authorization: authorization.as_json.merge(client_accumulated_points: authorization.client.cache_points)}, status: :ok
    else
      render json: adapter.errors, status: 400
    end
  end

  def confirm
    authorization =  Authorization.find(query[:authorization_id])
    manager = SaleFromAuthorization.new(authorization)
    if manager
      manager.create
      render json: {status: :ok}, status: :ok
    else
      render json: manager.errors, status: 400
    end
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show]
  before_action :set_supplier
  before_action :only_authorize_admin!, except: [:index, :show]

  # GET users/1/sales
  def index
    @filter = SaleFilter.new(filter_params)
    @sales = @filter.call(current_user).page(params[:page])

    respond_to do |format|
      format.html {
        render layout: 'public' if normal_user?
      }
      format.xlsx
    end
  end

  #GET users/1/sales/1
  def show
    if normal_user?
      render 'show', layout: 'public'
    end
  end

  # GET users/1/sales/new
  def new
    @sale = Sale.new
  end

  # POST users/1/sales
  # Recibe el id de una autorización por parámetro, y crea una venta.
  def create
    authorization = Authorization.find(params[:authorization])
    if authorization.created_at > Const::AUTHORIZATION_EXPIRATION_LIMIT.minutes.ago
      manager = SaleFromAuthorization.new(authorization)
      @sale = manager.create
      redirect_to [current_user.supplier, current_user, @sale], notice: 'La venta ha sido creada correctamente.'
    else
      render text: 'La autorización ha expirado'
    end
  end

  def destroy
    # TODO Charlar si es necesario
  end

  def edit
    # TODO Charlar si es necesario
  end

  private

  def set_sale
    @sale = Sale.find(params[:id])
  end

  def sale_params
    params.require(:sale).permit(:seller_id, :client_id, :health_insurance_id, :coinsurance_id, sale_products_attributes: [:id, :product_id, :amount, :cost, :discount, :client_points, :seller_points, :_destroy])
  end

  def filter_params
    if params[:sale_filter]
      params.require(:sale_filter).permit(:supplier_id, :seller_id, :client_id, :start_date, :finish_date, :laboratory_id, :drug_id)
    end
  end

  def set_supplier
    @supplier = current_user.supplier
  end

end

app/views/sales/_filter.html.erb
<div id="js-salesFilter">

  <% url = normal_user? ? my_purchases_path : [@supplier, current_user, :sales] %>

  <%= form_for @filter, url: url, method: :get do |f| %>

      <%= hidden_field_tag :format, '', id: 'js-salesFormFormat' %>

      <div class="row">

        <% if god? %>
            <!-- PRESTADOR -->
            <div class="col-md-3">
              <fieldset class="form-group">
                <%= f.label :supplier_id %>
                <%= f.collection_select :supplier_id, Supplier.active,
                                        :id, :name, {include_blank: true}, {class: 'form-control'} %>
              </fieldset>
            </div>
        <% end %>

        <% if admin? || god? %>
            <!-- VENDEDOR -->
            <div class="col-md-3">
              <fieldset class="form-group">
                <%= f.label :seller_id %>
                <%= f.collection_select :seller_id, User.visible_sellers_for(current_user),
                                        :id, :fullname, {include_blank: true}, {class: 'form-control'} %>
              </fieldset>
            </div>
        <% end %>

        <% unless normal_user? %>
            <!-- USUARIO -->
            <div class="col-md-2">
              <fieldset class="form-group">
                <%= f.label :client_id %>
                <%= f.hidden_field :client_id, class: 'select2',
                                   data: {behavior: 'searchClient',
                                          url: search_users_path,
                                          'record-id' => @filter.client_id,
                                          'record-text' => @filter.card_number} %>
              </fieldset>
            </div>
        <% end %>

        <!-- FECHAS -->
        <div class="col-md-2">
          <fieldset class="form-group">
            <%= f.label :start_date %>
            <div class='input-group date datepicker'>
              <%= f.text_field :start_date, class: 'form-control', value: @filter.start_date %>
              <span class="input-group-addon">
              <span class="fa fa-calendar"></span>
            </span>
            </div>
          </fieldset>
        </div>

        <div class='col-md-2'>
          <fieldset class="form-group">
            <%= f.label :finish_date %>
            <div class='input-group date datepicker'>
              <%= f.text_field :finish_date, class: 'form-control', value: @filter.finish_date %>
              <span class="input-group-addon">
              <span class="fa fa-calendar"></span>
            </span>
            </div>
          </fieldset>
        </div>
      </div>

      <div class="row">

        <% unless normal_user? %>
            <div class="col-md-3">
              <fieldset class="form-group">
                <%= f.label :laboratory_id %>
                <%= f.hidden_field :laboratory_id, class: 'select2',
                                   data: {behavior: 'searchLaboratory',
                                          url: search_laboratories_path,
                                          'record-id' => @filter.laboratory_id,
                                          'record-text' => @filter.laboratory_name} %>
              </fieldset>
            </div>

            <div class="col-md-3">
              <fieldset class="form-group">
                <%= f.label :drug_id %>
                <%= f.hidden_field :drug_id, class: 'select2',
                                   data: {behavior: 'searchDrug',
                                          url: search_drugs_path,
                                          'record-id' => @filter.drug_id,
                                          'record-text' => @filter.drug_name} %>
              </fieldset>
            </div>
        <% end %>

        <div class="col-md-3">
          <fieldset class="form-group">
            <%= f.label :filter, '' %><br/>
            <%= f.submit 'Filtrar', class: 'btn btn-primary', data: {behavior: 'filter'} %>
            <%= f.submit 'Exportar', class: 'btn btn-info', data: {behavior: 'export'} %>
          </fieldset>
        </div>
      </div>

  <% end %>

</div>

app/views/sales/_form.html.erb
<div class="row">
  <div class="col-md-12" id="js-sale">
    <article class="box box-primary">
      <section class="box-body">

        <%= form_for [@supplier, current_user, @sale], url: authorizations_path, remote: true do |f| %>
            <% @sale.errors.full_messages.each do |message| %>
                <p><%= message %></p>
            <% end %>
            <div class="row">
              <div class='col-md-4'>
                <h4>Cliente</h4>
                <fieldset class="form-group">
                  <%= f.hidden_field :client_id, class: 'select2', auto_focus: true,
                                     data: {behavior: 'searchClient', url: search_users_path} %>
                </fieldset>
              </div>
              <div class='col-md-4'>
                <h4>Obra Social</h4>
                <fieldset class="form-group">
                  <%= f.hidden_field :health_insurance_id, class: 'select2',
                                     data: {behavior: 'searchHealthInsurance', url: search_health_insurances_path} %>
                </fieldset>
              </div>
              <div class='col-md-4'>
                <h4>Coseguro</h4>
                <fieldset class="form-group">
                  <%= f.hidden_field :coinsurance_id, class: 'select2',
                                     data: {behavior: 'searchCoinsurance', url: search_coinsurances_path} %>
                </fieldset>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <div id="js-productSales" class="product_sales form-group">
                  <%= f.fields_for :sale_products do |p| %>
                      <%= render 'sale_product_fields', f: p %>
                  <% end %>
                  <div class="links">
                    <%= link_to_add_association 'Agregar Producto', f, :sale_products, class: 'btn btn-default' %>
                  </div>
                </div>
              </div>
            </div>

            <div class="actions">
              <%= f.submit 'Autorizar', class: 'btn btn-primary', id: 'js-clearAuthorizationContent', data: {'disable-with' => 'Cargando...'} %>
            </div>
        <% end %>

      </section>
    </article>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div id="js-authorization">
    </div>
  </div>
</div>

app/views/sales/_sale.html.erb
<tr>
  <td><%= sale.seller %></td>
  <% unless @supplier %>
      <td><%= sale.seller.supplier %></td>
  <% end %>
  <td><%= sale.client %></td>
  <td><%= sale.client.card_number %></td>
  <td><%= sale.created_at.strftime('%d-%m-%Y %H:%M:%S') %></td>
  <td><%= number_to_currency(sale.total) %></td>
  <td class="pull-right">
    <% unless normal_user? %>
        <%= link_to 'Ir a la autorización', authorization_path(sale.authorization), class: 'btn btn-xs btn-default' %>
    <% end %>
    <%= link_to 'Ver', user_sale_path(current_user, sale), class: 'btn btn-xs btn-primary' %>
  </td>
</tr>

app/views/sales/_sale_product_fields.html.erb
<div class="nested-fields">
  <div class="row">

    <div class="col-md-9">
      <fieldset class="form-group">
        <%= f.label :product %>
        <%= f.hidden_field :product_id, class: 'select2',
                           data: {behavior: 'searchProduct', url: search_products_path,
                                  record_id: f.object.product_id, record_text: f.object.product.try(:name)} %>
      </fieldset>
    </div>

    <div class="col-md-3">

      <div class="row">
        <div class="col-md-5">
          <fieldset class="form-group">
            <%= f.label :amount %>
            <%= f.text_field :amount, class: 'form-control', required: true, placeholder: 'Cantidad' %>
          </fieldset>
        </div>
        <div class="col-md-5">
          <fieldset class="form-group">
            <%= f.label :cost %>
            <%= f.text_field :cost, class: 'form-control js-cost', required: true, placeholder: 'Costo' %>
          </fieldset>
        </div>

        <div class="col-md-2 text-center">
          <fieldset class="form-group css-sales-btnDelete">
            <%= link_to_remove_association f, class: 'btn btn-danger btn-xs margin-top-5' do %>
                <i class="fa fa-trash"></i>
            <% end %>
          </fieldset>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/sales/index.html.erb
<header class="content-header">
  <% unless current_user.is?('normal_user') %>
      <%= link_to 'Nueva Venta', [:new, @supplier, current_user, :sale],
                  class: 'btn btn-primary pull-right' %>
  <% end %>
  <h1>Ventas</h1>
</header>

<!-- Main content -->
<section class="content">
  <article class="box box-primary">
    <section class="box-body">

      <%= render 'filter' %>

      <table class="table">
        <thead>
        <tr>
          <th>Vendedor</th>
          <% unless @supplier %>
              <th>Prestador</th>
          <% end %>
          <th>Cliente</th>
          <th>Tarjeta</th>
          <th>Fecha y hora</th>
          <th>Total</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <%= render @sales %>
        </tbody>
      </table>

      <%= paginate @sales %>

    </section>
  </article>
</section>

app/views/sales/new.html.erb
<header class="content-header">
  <%= link_to 'Volver', user_sales_path,
              class: 'btn btn-default pull-right' %>
  <h1>Nueva Venta</h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>

app/views/sales/show.html.erb
<header class="content-header">
  <% if normal_user? %>
      <%= link_to 'Volver', my_purchases_path, class: 'btn btn-default pull-right' %>
  <% else %>
      <%= link_to 'Volver', user_sales_path, class: 'btn btn-default pull-right' %>
  <% end %>
  <h1>Información de la venta <strong>#<%= @sale.id %></strong></h1>
</header>

<section class="content">
  <article class="box box-primary">
    <section class="box-body">

      <div class="row">
        <div class="col-md-4">
          <h5>Vendedor: <strong><%= @sale.seller %></strong></h5>
        </div>
        <div class="col-md-4">
          <h5>Prestador: <strong><%= @sale.seller.supplier %></strong></h5>
        </div>
        <div class="col-md-4">
          <h5>Cliente: <strong><%= @sale.client %></strong></h5>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h5>Detalle de descuentos aplicados:</h5>
          <table id="css-authorizations-table" class="table table-striped table-condensed">
            <thead>
            <tr>
              <th>Nombre</th>
              <th><span data-toggle="tooltip" data-placement="top" title="Cantidad">Cant.</span></th>
              <th><span data-toggle="tooltip" data-placement="top" title="Costo Unitario">CU</span></th>
              <th><span data-toggle="tooltip" data-placement="top" title="Descuento aplicado">Dto</span></th>
              <th><span data-toggle="tooltip" data-placement="top" title="Puntos Cliente">Pts. Cliente</span></th>
              <% unless normal_user? %>
                <th><span data-toggle="tooltip" data-placement="top" title="Puntos Vendedor">Pts. Vendedor</span></th>
              <% end %>
              <th>Total</th>
            </tr>
            </thead>
            <tbody>
            <% @sale.sale_products.each do |product| %>
                <tr>
                  <td><%= product.product.to_s %></td>
                  <td><%= product.amount %></td>
                  <td><%= number_to_currency(product.cost) %></td>
                  <td><%= number_to_percentage(product.discount, precision: 0) %></td>
                  <td><%= product.client_points %></td>
                  <% unless normal_user? %>
                    <td><%= product.seller_points %></td>
                  <% end %>
                  <td><%= number_to_currency(product.total) %></td>
                </tr>
            <% end %>
            </tbody>
            <tfoot>
              <tr>
                <td colspan="4"><strong>TOTAL:</strong></td>
                <td><strong><%= @sale.client_points %></strong></td>
                <% unless normal_user? %>
                  <td><strong><%= @sale.seller_points %></strong></td>
                <% end %>
                <td><strong><%= number_to_currency(@sale.total) %></strong></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>

    </section>
  </article>

  <% unless normal_user? %>
      <%= link_to 'Nueva venta', [:new, @supplier, current_user, :sale], class: 'btn btn-success btn-block' %>
  <% end %>

</section>